name: Meiji-Primitives

on: [push, pull_request]

jobs:
  Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt-get install binutils-dev clang-14 make cmake

  ProfileDebug:
    runs-on: ubuntu-latest
    needs: Dependencies
    steps:
      - name: Configure
        run:  cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DTSAN:STRING= -DASAN:STRING= -DTWIST_FIBERS:STRING= -DTWIST_FAST_FIBER_QUEUES:STRING= -DTWIST_PRINT_STACKS:STRING= -DTWIST_FAULTY:STRING= -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ -S. -B./build -G "Unix Makefiles"
      - name: Build
        run:  cmake --build /home/bakalover/code/concurrency/chime/build --config Debug --target chime chime_tests -j 10 --
      - name: Run
        run: ./build/tests/chime_tests