name: Chime

on: [push, pull_request]

jobs:
 Testing:
    runs-on: ubuntu-latest
    container: Dockerfile
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run:  cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DTSAN:STRING= -DASAN:STRING= -DTWIST_FIBERS:STRING= -DTWIST_FAST_FIBER_QUEUES:STRING= -DTWIST_PRINT_STACKS:STRING= -DTWIST_FAULTY:STRING= -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang-14 -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++-14 -S. -B./build -G "Unix Makefiles"
      - name: Build
        run:  cmake --build ./build --config Debug --target chime chime_tests -j 10 --
      - name: Run
        run: ./build/tests/chime_tests
