name: Chime

on: [push, pull_request]

jobs:
 Testing:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get install -y wget rsync
          sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository -y "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main"
          sudo wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc | sudo apt-key add -
          sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal main'
          sudo apt-get update
          sudo apt-get -y install build-essential ninja-build linux-tools-common linux-tools-generic  binutils-dev g++-12 clang-14 clang-format-14 clang-tidy-14 cmake build-essential libc++-14-dev libc++abi-14-dev libclang-rt-14-dev libdwarf-dev libdw-dev 
      - uses: actions/checkout@v2
      - name: Configure
        run:  cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DTSAN:STRING= -DASAN:STRING= -DTWIST_FIBERS:STRING= -DTWIST_FAST_FIBER_QUEUES:STRING= -DTWIST_PRINT_STACKS:STRING= -DTWIST_FAULTY:STRING= -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang-14 -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++-14 -S. -B./build -G "Unix Makefiles"
      - name: Build
        run:  cmake --build ./build --config Debug --target chime chime_tests -j 10 --
      - name: Run
        run: ./build/tests/chime_tests
